### ISSUE TITLE
Selected day issue

### ISSUE THREAD

**Issue by enheit** [kesarion/angular2-air-datepicker#1]
Hello, @kesarion. I have found an issue in your package. If i select the day of month, for example it will be 31 January, and click the 'next month' button ' it shows me an error: `"./AirDatepicker class AirDatepicker - inline template:11:12 caused by: Cannot set property 'selected' of undefined".` The reason why this is happening: Your package try to mark 'selected' day which is not exist in the next month. February doesn't contain 31 days. You should fix it by adding a condition.

**Comment by kesarion** [comment]
@enheit Good catch! I'll add check soon.
