### ISSUE TITLE
Date shows incorrect day and calendar 

### ISSUE THREAD

**Issue by bernard4uece** [kesarion/angular2-air-datepicker#14]
Dates are displaying wrong in the calendar after the recent commits and in the version 1.1.2. And I rolled back to version 1.0.0, now the calendar at least shows correct dates. 

![image](https://user-images.githubusercontent.com/41011210/44027753-99189b3c-9ec5-11e8-8242-541c0f1d9117.png)

See below, correct days for Aug month displayed by system calendar.

![image](https://user-images.githubusercontent.com/41011210/44027993-7783ee30-9ec6-11e8-9afa-de21e569c795.png)

**Comment by kesarion** [comment]
@bernard4uece Could you tell me if v1.1.3 resolves the issue for you?

**Comment by bernard4uece** [comment]
I will do, thanks for pushing fixes.

**Comment by bernard4uece** [comment]
the latest version has addressed all the issues. Thanks again!!
