### ISSUE TITLE
How to put this on a popover?

### ISSUE THREAD

**Issue by whizkidwwe1217** [kesarion/angular2-air-datepicker#16]
Currently, the picker is already visible on the page. Is there a config that makes this behave like a dropdown?

**Comment by bernard4uece** [comment]
@whizkidwwe1217 does this link [help](https://stackblitz.com/edit/angular6-air-datepicker-demo)

**Comment by whizkidwwe1217** [comment]
@bernard4uece Awesome! Thanks! 😊
