### ISSUE TITLE
Last day of enabledDateRanges don't trigger airChange

### ISSUE THREAD

**Issue by rozumny** [kesarion/angular2-air-datepicker#19]
How to reproduce: 
1) initialize option with following data: this.options = {
      timepicker: false,
      enabledDateRanges: [
        { start: new Date(now - 3 * days), end: new Date(now -2 * days) }
      ]
    };
2) bind on date changed action 
 (airChange)="dateChanged($event)
3) click on enabled date in calendar
4) nothing happen, dateChanged is not called

**Comment by kesarion** [comment]
@rozumny Could you try setting the start date at the very beginning of the day (00:00) and the end date at the end of the day (23:59)? For timezone and writing-less-code reasons, that's currently the best way to make sure it works all the time, anywhere.

The examples might need to be updated, and my little recommendation about setting these dates at the start/end of their respective days might need to be more of a mandatory rule; that or it could be handled auto-magically by the component... which would mean introducing a lot more scenarios than I'd like right now. For the time being, see if setting the limits as described works for you.

**Comment by rozumny** [comment]
works perfect, thank you!
