### ISSUE TITLE
Add russian language

### ISSUE THREAD

**Issue by Spirka** [kesarion/angular2-air-datepicker#28]
Hello! Can you add new language (russian). I need to add the follow code to language library: 
 ['ru', new AirLanguage(
        ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
        ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
        ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']
    )] as [string, AirLanguage],
?

**Comment by kesarion** [comment]
@Spirka I could have sworn Russian was already in there!

I've added it now along with some fixes to Travis in v1.4.2. It should already be available on NPM. I didn't test it manually, so tell me if everything's all right. If it's fine, you can go ahead and close this issue :)

**Comment by Spirka** [comment]
Month numbers not visible. Days of week are good.
![Screenshot_1](https://user-images.githubusercontent.com/31223035/74722545-2c268180-524a-11ea-9c53-b0114d908d2d.png)

**Comment by kesarion** [comment]
Well, I just built and served the `angular2-air-datepicker-app` project included with the project on github and it works just fine with `language: 'ru'`:

![Annotation 2020-02-18 121146](https://user-images.githubusercontent.com/784663/74726435-1fa12980-5248-11ea-87df-ef4ae31b7edb.png)

See if that project works for you and continue debugging from there (the console may contain something interesting).

**Comment by Spirka** [comment]
Thank you so match. I'll find a mistake in my code. 
One more question please, can this calendar be used in a project on angular with formControl?

**Comment by kesarion** [comment]
Forms are completely up to you, you are in charge of what date you set on the date component and what you do with the date you receive from it. You can also make use of the two-way binding functionality to have the same date in whatever form/input you use, without you having to change it, though you do need to format it (this component only gives you a Date Object), which means you shouldn't make it editable or else you would need to validate and parse it on user input (clicks) back to a Date Object and re-set it on the component.

**Comment by Spirka** [comment]
Thank you. It works! I'm so gratefuul to you!
