### ISSUE TITLE
Implement date range selection

### ISSUE THREAD

**Issue by kesarion** [kesarion/angular2-air-datepicker#7]
An issue to track the range selection feature.

**Comment by Razzeee** [comment]
So this references this? http://t1m0n.name/air-datepicker/docs/#example-range

And does not work with the angular version?

**Comment by kesarion** [comment]
@Razzeee Yes. It hasn't been implemented yet; this is a more sophisticated feature that few people use. In the meantime, using two datepickers placed in dropdowns is a viable workaround.

It does help to know there's some interest in this feature, though. Perhaps I'll have some time to work on it soon.

**Comment by Dheyson** [comment]
@kesarion Do we have some preview if it`s gonna be implemented the range selection feature?
Do you know any other repository which might suit well for angular?

**Comment by kesarion** [comment]
Available in 2.0.0! 🎉

I haven't had the time to create automated tests, but I did a lot of manual testing and I think it works fine for most use cases!
